spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql:///seata_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qw23e
    jdbcUrl: ${spring.datasource.url}
  cloud:
    alibaba:
      seata:
        # 当前模块在哪个事务组中
        tx-service-group: order_tx_group

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.learn.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.learn.mapper: debug

ribbon:
  MaxAutoRetriesNextServer: 0  # 默认1
